/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108654-gfd5c273f26-20221016"
#endif /* AVUTIL_FFVERSION_H */
